codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        # Adjust target coverage as needed
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        # Require new code to have at least 80% coverage
        target: 80%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no

ignore:
  - "tests/**/*"
  - "**/*_test.py"
  - "**/test_*.py"
  - "src/cli.py" # CLI entry point
  - "src/streamlit_app.py" # Streamlit app is hard to test
  - "database/**/*"
  - "scripts/**/*"
