version: "3.8"

services:
  polibase:
    build: .
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud # GCP認証情報をマウント
    environment:
      - ENV_VAR_NAME=env_var_value # 必要な環境変数を設定
      - DATABASE_URL=postgresql://polibase_user:polibase_password@postgres:5432/polibase_db
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=trust-chain-828ad
    ports:
      - "8000:8000" # 必要に応じてポートを設定
      - "8501:8501" # Streamlit用ポート
    stdin_open: true # 追加
    tty: true # 追加
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: polibase_db
      POSTGRES_USER: polibase_user
      POSTGRES_PASSWORD: polibase_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/seed_governing_bodies.sql:/docker-entrypoint-initdb.d/seed_governing_bodies.sql:ro
      - ./database/seed_political_parties.sql:/docker-entrypoint-initdb.d/seed_political_parties.sql:ro
      - ./database/seed_conferences.sql:/docker-entrypoint-initdb.d/seed_conferences.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polibase_user -d polibase_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
