[tool.poetry]
name = "polibase"
version = "0.1.0"
description = ""
authors = ["okodoon <31516823+okodoon@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain-google-genai = "^2.0.11"
langchain = "^0.3.20"
langgraph = "^0.3.5"
pypdfium2 = "^4.30.1"
python-dotenv = "^1.0.1"
duckdb = "^1.2.1"
unittest = "^0.0"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
