#!/bin/bash

# Generate .streamlit/secrets.toml with dynamic port numbers based on git worktree directory
# This script should be run after setup-worktree-ports.sh

set -e

# Get the current directory
CURRENT_DIR=$(pwd)

# Get the git worktree directory name (last part of path)
WORKTREE_NAME=$(basename "$CURRENT_DIR")

# Function to calculate port offset from worktree name (same as setup-worktree-ports.sh)
calculate_port_offset() {
    local name="$1"
    local hash=0
    for (( i=0; i<${#name}; i++ )); do
        char_code=$(printf '%d' "'${name:$i:1}")
        hash=$(( (hash + char_code) % 100 ))
    done
    echo $(( hash * 10 ))
}

# Calculate offset for this worktree
OFFSET=$(calculate_port_offset "$WORKTREE_NAME")

# Define base port
BASE_STREAMLIT_PORT=8501

# Calculate actual port
STREAMLIT_PORT=$(( BASE_STREAMLIT_PORT + OFFSET ))

# Create .streamlit directory if it doesn't exist
mkdir -p .streamlit

# Check if secrets.toml already exists
if [ -f .streamlit/secrets.toml ]; then
    echo "⚠️  .streamlit/secrets.toml already exists."

    # Check if it has placeholder values
    if grep -q "REPLACE_WITH_YOUR" .streamlit/secrets.toml || grep -q "YOUR_CLIENT" .streamlit/secrets.toml; then
        echo "   Detected placeholder values. Recreating with environment variables..."
        rm .streamlit/secrets.toml
    else
        echo "   Recreating with ASCII-only content and port $STREAMLIT_PORT..."
        rm .streamlit/secrets.toml
    fi
fi

# Create secrets.toml (either new or recreating)
if [ ! -f .streamlit/secrets.toml ]; then
    echo "📝 Creating .streamlit/secrets.toml for worktree: $WORKTREE_NAME"

    # Create secrets.toml with dynamic port
    # Load environment variables from .env if it exists
    if [ -f .env ]; then
        set -a
        source .env
        set +a
    fi

    cat > .streamlit/secrets.toml << 'EOF'
# Streamlit Authentication Configuration
# This file is gitignored and auto-generated by scripts/setup-streamlit-secrets.sh

[auth]
# OAuth 2.0 Redirect URI (worktree-specific port)
redirect_uri = "http://localhost:STREAMLIT_PORT_PLACEHOLDER/oauth2callback"

# Cookie signing secret
cookie_secret = "COOKIE_SECRET_PLACEHOLDER"

# Google OAuth 2.0 Client ID
client_id = "CLIENT_ID_PLACEHOLDER"

# Google OAuth 2.0 Client Secret
client_secret = "CLIENT_SECRET_PLACEHOLDER"

# Google OpenID Connect metadata URL
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
EOF

    # Replace placeholders with actual values
    if [ "$(uname)" = "Darwin" ]; then
        # macOS
        sed -i '' "s|STREAMLIT_PORT_PLACEHOLDER|$STREAMLIT_PORT|g" .streamlit/secrets.toml
        sed -i '' "s|COOKIE_SECRET_PLACEHOLDER|${STREAMLIT_COOKIE_SECRET:-REPLACE_WITH_YOUR_RANDOM_SECRET}|g" .streamlit/secrets.toml
        sed -i '' "s|CLIENT_ID_PLACEHOLDER|${GOOGLE_OAUTH_CLIENT_ID:-YOUR_CLIENT_ID.apps.googleusercontent.com}|g" .streamlit/secrets.toml
        sed -i '' "s|CLIENT_SECRET_PLACEHOLDER|${GOOGLE_OAUTH_CLIENT_SECRET:-YOUR_CLIENT_SECRET}|g" .streamlit/secrets.toml
    else
        # Linux
        sed -i "s|STREAMLIT_PORT_PLACEHOLDER|$STREAMLIT_PORT|g" .streamlit/secrets.toml
        sed -i "s|COOKIE_SECRET_PLACEHOLDER|${STREAMLIT_COOKIE_SECRET:-REPLACE_WITH_YOUR_RANDOM_SECRET}|g" .streamlit/secrets.toml
        sed -i "s|CLIENT_ID_PLACEHOLDER|${GOOGLE_OAUTH_CLIENT_ID:-YOUR_CLIENT_ID.apps.googleusercontent.com}|g" .streamlit/secrets.toml
        sed -i "s|CLIENT_SECRET_PLACEHOLDER|${GOOGLE_OAUTH_CLIENT_SECRET:-YOUR_CLIENT_SECRET}|g" .streamlit/secrets.toml
    fi

    echo "✅ Created .streamlit/secrets.toml"
    echo "   Port: $STREAMLIT_PORT"
    echo "   Redirect URI: http://localhost:$STREAMLIT_PORT/oauth2callback"
    echo ""
    echo "⚠️  Next steps:"
    echo "   1. Set environment variables in .env:"
    echo "      STREAMLIT_COOKIE_SECRET=<random_secret>"
    echo "      GOOGLE_OAUTH_CLIENT_ID=<your_client_id>"
    echo "      GOOGLE_OAUTH_CLIENT_SECRET=<your_client_secret>"
    echo "   2. Or manually edit .streamlit/secrets.toml"
    echo "   3. Add this redirect URI to Google Cloud Console:"
    echo "      http://localhost:$STREAMLIT_PORT/oauth2callback"
fi

echo ""
echo "📌 Don't forget to add the following URIs to Google Cloud Console:"
echo "   OAuth 2.0 Client ID → Authorized redirect URIs:"
echo "   - http://localhost:$STREAMLIT_PORT/oauth2callback"
echo ""
echo "💡 Tip: Register multiple ports (8501-8600) in Google Cloud Console"
echo "   to avoid reconfiguration for each worktree."
