name: CI - Quick Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  quick-checks:
    name: Quick validation checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Check Python syntax
        run: |
          python -m py_compile src/**/*.py tests/**/*.py || true

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Check imports and basic structure
        run: |
          uv run python -c "
          import sys
          sys.path.insert(0, '.')
          try:
              # srcディレクトリ内のモジュールを確認
              from src import exceptions
              from src import cli
              from src.database import base_repository
              from src.application import usecases
              from src.domain import entities
              print('✅ Basic imports successful')
          except ImportError as e:
              print(f'❌ Import error: {e}')
              sys.exit(1)
          "

      - name: Run Ruff format check
        run: |
          uv run ruff format --check src/ tests/

      - name: Run Ruff linter
        run: |
          uv run ruff check src/ tests/
        continue-on-error: true

      - name: Check for security issues with bandit
        run: |
          uv run bandit -r src/ -ll -i -x "*/tests/*"
        continue-on-error: true
